#!/usr/bin/env python3
"""
Prepare a standardized primitive Si structure and all QE inputs for practice 3.

Core idea:
    one structure -> three different k-point tasks

    uniform mesh       -> SCF charge density
    high-symmetry path -> bands E_n(k)
    dense uniform mesh -> DOS / PDOS

SeeK-path is used to standardize the primitive cell and generate the
high-symmetry path. The SCF and DOS meshes are NOT generated by SeeK-path.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import os

import seekpath
from pymatgen.core import Structure, Element


def fmt_vec(v):
    return " ".join(f"{x: .12f}" for x in v)


def qe_structure_block(structure: Structure) -> str:
    lines = ["CELL_PARAMETERS angstrom"]
    for v in structure.lattice.matrix:
        lines.append(fmt_vec(v))
    lines.append("")
    lines.append("ATOMIC_POSITIONS crystal")
    for site in structure:
        x, y, z = site.frac_coords
        lines.append(f"{site.specie.symbol:2s} {x: .12f} {y: .12f} {z: .12f}")
    return "\n".join(lines)


def qe_header(calculation, outdir, pseudo_dir, pseudo_file, structure, nbnd=None):
    nbnd_line = f"  nbnd = {nbnd}\n" if nbnd is not None else ""
    return f"""&CONTROL
  calculation = '{calculation}'
  prefix = 'si'
  pseudo_dir = '{pseudo_dir}'
  outdir = '{outdir}'
  tstress = .true.
  tprnfor = .true.
/
&SYSTEM
  ibrav = 0
  nat = {len(structure)}
  ntyp = 1
  ecutwfc = 40.0
  ecutrho = 160.0
{nbnd_line}  occupations = 'fixed'
/
&ELECTRONS
  conv_thr = 1.0d-10
  mixing_beta = 0.7
/
ATOMIC_SPECIES
Si 28.0855 {pseudo_file}

{qe_structure_block(structure)}
"""


def main():
    p = argparse.ArgumentParser()
    p.add_argument("cif", help="Input CIF")
    p.add_argument("--pseudo-dir", default=os.environ.get("QE_PSEUDO_DIR", "/home/md/Software/qe-7.5/pseudo"))
    p.add_argument("--pseudo-file", default=os.environ.get("QE_PSEUDO_FILE", "Si_r.upf"))
    p.add_argument("--scf-grid", type=int, default=6)
    p.add_argument("--dos-grid", type=int, default=12)
    p.add_argument("--reference-distance", type=float, default=0.03)
    args = p.parse_args()

    root = Path(__file__).resolve().parents[1]
    inputs = root / "inputs"
    generated = root / "generated"
    inputs.mkdir(exist_ok=True)
    generated.mkdir(exist_ok=True)

    s = Structure.from_file(args.cif)
    sp_in = (
        s.lattice.matrix,
        s.frac_coords,
        [site.specie.Z for site in s],
    )

    # Explicit path avoids ambiguity at discontinuous SeeK-path branches.
    res = seekpath.get_explicit_k_path(
        sp_in,
        with_time_reversal=True,
        reference_distance=args.reference_distance,
        symprec=1.0e-5,
    )

    primitive = Structure(
        lattice=res["primitive_lattice"],
        species=[Element.from_Z(int(z)) for z in res["primitive_types"]],
        coords=res["primitive_positions"],
        coords_are_cartesian=False,
    )
    primitive.to(filename=str(generated / "si_seekpath_primitive.cif"))

    # Human-readable path information.
    with open(generated / "seekpath_summary.txt", "w", encoding="utf-8") as f:
        f.write(f"bravais_lattice = {res['bravais_lattice']}\n")
        f.write(f"bravais_lattice_extended = {res['bravais_lattice_extended']}\n\n")
        f.write("High-symmetry points (fractional reciprocal coordinates):\n")
        for label, xyz in res["point_coords"].items():
            f.write(f"{label:10s} {xyz[0]: .8f} {xyz[1]: .8f} {xyz[2]: .8f}\n")
        f.write("\nRecommended path:\n")
        for start, stop in res["path"]:
            f.write(f"{start} -> {stop}\n")

    # Label indices correspond to the explicit path used in the bands input.
    with open(generated / "seekpath_labels.tsv", "w", encoding="utf-8") as f:
        f.write("index0\tindex1\tlinear_coordinate\tlabel\n")
        for i, (x, label) in enumerate(zip(
            res["explicit_kpoints_linearcoord"],
            res["explicit_kpoints_labels"]
        )):
            if label:
                f.write(f"{i}\t{i+1}\t{x:.12f}\t{label}\n")

    # ---------- Branch 1: SCF ----------
    scf = qe_header(
        "scf", "./tmp/scf", args.pseudo_dir, args.pseudo_file, primitive
    )
    scf += f"""
K_POINTS automatic
{args.scf_grid} {args.scf_grid} {args.scf_grid} 1 1 1
"""
    (inputs / "si_scf.in").write_text(scf, encoding="utf-8")

    # ---------- Branch 2: bands along SeeK-path ----------
    bands = qe_header(
        "bands", "./tmp/bands", args.pseudo_dir, args.pseudo_file, primitive, nbnd=12
    )
    kp = res["explicit_kpoints_rel"]
    bands += "\nK_POINTS crystal\n"
    bands += f"{len(kp)}\n"
    for k in kp:
        bands += f"{k[0]: .12f} {k[1]: .12f} {k[2]: .12f} 1.0\n"
    (inputs / "si_bands.in").write_text(bands, encoding="utf-8")

    # ---------- Branch 3: dense uniform NSCF for DOS / PDOS ----------
    nscf = qe_header(
        "nscf", "./tmp/dos", args.pseudo_dir, args.pseudo_file, primitive, nbnd=12
    )
    nscf += f"""
K_POINTS automatic
{args.dos_grid} {args.dos_grid} {args.dos_grid} 1 1 1
"""
    (inputs / "si_nscf_dos.in").write_text(nscf, encoding="utf-8")

    # ---------- Post-processing ----------
    (inputs / "si_bands_pp.in").write_text("""&BANDS
  prefix = 'si'
  outdir = './tmp/bands'
  filband = './results/bands/si_bands.dat'
  lsym = .false.
  no_overlap = .true.
/
""", encoding="utf-8")

    (inputs / "si_projwfc_bands.in").write_text("""&PROJWFC
  prefix = 'si'
  outdir = './tmp/bands'
  lsym = .false.
  filproj = './results/bands/si_proj'
/
""", encoding="utf-8")

    (inputs / "si_dos_pp.in").write_text("""&DOS
  prefix = 'si'
  outdir = './tmp/dos'
  fildos = './results/dos/si.dos'
  bz_sum = 'smearing'
  ngauss = 0
  degauss = 0.01
  DeltaE = 0.02
/
""", encoding="utf-8")

    (inputs / "si_projwfc_dos.in").write_text("""&PROJWFC
  prefix = 'si'
  outdir = './tmp/dos'
  filpdos = './results/dos/si'
  ngauss = 0
  degauss = 0.01
  DeltaE = 0.02
/
""", encoding="utf-8")

    print("Prepared:")
    for name in [
        "si_scf.in", "si_bands.in", "si_nscf_dos.in",
        "si_bands_pp.in", "si_projwfc_bands.in",
        "si_dos_pp.in", "si_projwfc_dos.in",
    ]:
        print("  inputs/" + name)
    print("  generated/si_seekpath_primitive.cif")
    print("  generated/seekpath_summary.txt")
    print("  generated/seekpath_labels.tsv")
    print()
    print("Three k-point roles:")
    print(f"  SCF  : {args.scf_grid}x{args.scf_grid}x{args.scf_grid} shifted uniform mesh")
    print("  bands: explicit SeeK-path")
    print(f"  DOS  : {args.dos_grid}x{args.dos_grid}x{args.dos_grid} shifted dense uniform mesh")


if __name__ == "__main__":
    main()
